/**
 * Platterly's master catalog of common Indian catering dishes (AJ, 2026-10-10). Built from the Bhandary's Kitchen
 * menus (corporate, kids, veg, non-veg, premium veg and non-veg, North and South Indian wedding), with every dish
 * listed once: spelling variants and repeats across menus are merged, and "A / B" options are split into their own
 * dishes. Pure data with no imports, so the seed script can load it directly.
 *
 * Each line is "Dish name | short description". No prices: a caterer sets their own when they add a dish.
 */
export type CatalogFoodType = "VEGETARIAN" | "NON_VEGETARIAN";

export interface CatalogSeed {
  name: string;
  description: string;
  foodType: CatalogFoodType;
  categoryName: string;
}

const V: CatalogFoodType = "VEGETARIAN";
const N: CatalogFoodType = "NON_VEGETARIAN";

const SECTIONS: [category: string, foodType: CatalogFoodType, lines: string[]][] = [
  ["Beverages", V, [
    "Mint Lemon Fizz | Sparkling lemon cooler with fresh mint",
    "Hawaiian Blue | Bright blue citrus mocktail over ice",
    "Jal Jeera | Tangy cumin and mint cooler",
    "Mojito | Virgin mojito with lime and mint, in lemon, orange or strawberry",
    "Fruit Punch | Chilled mixed fruit punch",
    "Chilli Guava | Guava juice with a spicy chilli kick",
    "Butter Milk | Spiced churned yogurt drink",
    "Cranberry Spritzer | Tart cranberry with soda and lime",
    "Masala Lemonade | Lemonade with chaat masala and roasted cumin",
    "Litchi Delight | Sweet litchi cooler served chilled",
    "Tangy Mango | Mango cooler with a lime twist",
    "Cucumber Lime Mint Cooler | Cool cucumber, lime and mint refresher",
    "Virgin Watermelon Margarita | Watermelon and lime slush with a salted rim",
    "Arabian Grape Juice | Chilled grape juice with a hint of spice",
    "Virgin Sangria | Fruit-infused non-alcoholic sangria",
    "Atomic Cat | Layered citrus and berry mocktail",
    "Watermelon Juice | Fresh pressed watermelon juice",
    "Pineapple Mint Cooler | Pineapple juice shaken with mint",
    "Sweet Lime Juice | Fresh mosambi juice",
    "Musk Melon Juice | Fresh pressed musk melon juice",
    "Fresh Lime Soda | Lime soda, sweet, salted or mixed",
    "Kiwi Cooler | Kiwi and lime sparkler",
    "Aam Panna | Raw mango cooler with roasted cumin",
    "Strawberry Punch | Strawberry fruit punch served chilled",
    "Lemon Juice | Fresh lemon juice, sweet or salted",
    "Green Island | Green apple and mint mocktail",
    "Mango Delight | Thick chilled mango drink",
    "Tea | Hot Indian masala tea",
    "Coffee | Hot filter or instant coffee",
    "Badam Milk | Warm milk with almonds and saffron",
    "Horlicks | Hot malted milk",
    "Black Tea | Hot tea served without milk",
    "Green Tea | Light hot green tea",
  ]],
  ["Soups", V, [
    "Cream of Tomato Soup | Smooth tomato soup finished with cream",
    "Hot & Sour Soup | Peppery, tangy vegetable soup",
    "Minestrone Soup | Italian vegetable and pasta soup",
    "Manchow Soup | Spicy Indo-Chinese soup topped with crispy noodles",
    "Lemon Coriander Soup | Light clear soup with lemon and fresh coriander",
    "Veg Clear Soup | Clear broth with finely cut vegetables",
    "Sweet Corn Soup | Creamy sweet corn soup with vegetables",
    "Dal Palak Ka Shorba | Light lentil and spinach soup",
    "Tomato Shorba | Spiced Indian-style tomato broth",
    "Tamatar Dhaniya Shorba | Tomato and coriander shorba",
    "Mulligatawny Soup | Lentil soup with mild curry spices",
    "Mushroom Soup | Smooth mushroom soup",
    "Cream of Mushroom Soup | Mushroom soup enriched with cream",
    "French Onion Soup | Slow-cooked onion soup with a cheesy crouton",
    "Tomato Soup | Classic tomato soup",
    "Broccoli Soup | Smooth broccoli soup",
    "Roasted Pumpkin Soup | Roasted pumpkin blended into a velvety soup",
    "Vegetable Cream Soup | Creamy soup of mixed vegetables",
    "Tomato Soup with Shredded Spinach | Tomato soup with fresh spinach ribbons",
    "Green Peas Puree with Rosemary | Green pea soup scented with rosemary",
  ]],
  ["Soups", N, [
    "Chicken Shorba | Light spiced chicken broth",
    "Sweet Corn Chicken Soup | Sweet corn soup with shredded chicken",
    "Hot & Sour Chicken Soup | Peppery, tangy soup with chicken",
    "Lemon Coriander Chicken Soup | Clear chicken soup with lemon and coriander",
    "Murgh Pudina Shorba | Chicken shorba flavoured with mint",
  ]],
  ["Starters", V, [
    // Paneer
    "Achari Paneer Tikka | Paneer cubes in pickle-spiced marinade, grilled in the tandoor",
    "Paneer Malai Tikka | Creamy, mildly spiced grilled paneer",
    "Peshawari Paneer Tikka | Paneer marinated in a rich Peshawari-style masala",
    "Hariyali Paneer Tikka | Paneer grilled in a mint and coriander marinade",
    "Mirch Masala Paneer Tikka | Spicy paneer tikka with a chilli masala coating",
    "Paneer Kalimirch Tikka | Paneer tikka with crushed black pepper",
    "Paneer Pudina Tikka | Paneer tikka in a fresh mint marinade",
    "Punjabi Paneer Tikka | Paneer tikka in a robust Punjabi spice marinade",
    "Azwaini Paneer Tikka | Paneer tikka flavoured with carom seeds",
    "Paneer Tikka | Paneer cubes marinated in spiced yogurt and grilled",
    "Paneer Manchurian | Fried paneer tossed in a tangy Manchurian sauce",
    "Paneer Chilli | Paneer tossed with capsicum and onion in chilli sauce",
    "Paneer Mint Chilli Crisp | Crispy paneer tossed with mint and chilli",
    "Paneer Golden Fry | Crumb-coated paneer fried until golden",
    "Paneer Satay | Skewered paneer with a peanut-style dip",
    "Crispy Corn | Fried corn kernels tossed with spices and herbs",
    "Honey Chilli Potato | Crispy potato strips in a sweet and spicy glaze",
    // Veg
    "Hara Bhara Kabab | Spinach, peas and potato patties, shallow fried",
    "Veg Cutlet | Crumb-fried mixed vegetable cutlet",
    "Baby Corn Tempura | Baby corn in a light crispy batter",
    "Palak Papri Kabab | Spinach and crisp papri kebab",
    "Aloo Corn Tikki | Potato and corn patties, shallow fried",
    "BBQ Pineapple | Pineapple chunks grilled with a spiced barbecue glaze",
    "Baby Corn Golden Fry | Crumb-coated baby corn fried golden",
    "Pesto Grilled Mushroom | Mushrooms grilled with basil pesto",
    "Veg Spring Roll | Crisp rolls filled with seasoned vegetables",
    "Cheese Balls | Crisp fried cheese and potato balls",
    "Cocktail Kachori | Bite-size crisp kachori with spicy filling",
    "Cocktail Samosa | Bite-size samosa with spiced potato filling",
    "Veg Lollipop | Vegetable mixture on a stick, crumb fried",
    "Aloo Methi Tikki | Potato and fenugreek patties",
    "Gobi Manchurian | Cauliflower florets in Manchurian sauce",
    "Baby Corn Manchurian | Baby corn tossed in Manchurian sauce",
    "Mushroom Manchurian | Mushrooms tossed in Manchurian sauce",
    "Gobi Chilli | Crisp cauliflower tossed in a spicy chilli sauce",
    "Baby Corn Chilli | Baby corn tossed in spicy chilli sauce",
    "Mushroom Chilli | Mushrooms tossed with capsicum and chilli sauce",
    "Crumb Fried Malai Balls | Creamy cheese balls coated in crumbs and fried",
    "Cheese Cigar | Cheese filled in a crisp pastry roll",
    "Cheese Roll | Crisp roll filled with melted cheese",
    "Corn Cheese Ball | Corn and cheese balls, crisp outside and gooey inside",
    "Moong Dal Pakori | Crisp lentil fritters",
    "Mini Kachori | Small crisp kachori with a spiced lentil filling",
    "Tandoori Phool | Cauliflower florets marinated and grilled in the tandoor",
    "Mushroom Galouti Kebab | Melt-in-the-mouth minced mushroom kebab",
    "Rajma Galouti Kebab | Soft red kidney bean kebab",
    "Cajun Spiced Potatoes | Baby potatoes roasted with Cajun spices",
    "Stuffed Mushroom | Mushroom caps stuffed with a cheesy filling",
    "Veg Seekh Kebab | Spiced mixed vegetable kebab grilled on skewers",
    "Tandoori Broccoli | Broccoli marinated in yogurt and spices, grilled",
    "Bharwan Mushroom | Stuffed mushrooms grilled in the tandoor",
    "Vegetable Tempura | Mixed vegetables in a light crisp batter",
    "Lahori Gobi | Cauliflower in a bold Lahori-style spice crust",
    "Lebanese Mushroom | Mushrooms in a Lebanese-style herb marinade",
    "Bharwan Punjabi Aloo | Stuffed potatoes grilled in the tandoor",
    "Chilly Garlic Grill Veg | Grilled vegetables with chilli and garlic",
    "Sabnam Ke Moti | Creamy vegetable pearls, lightly fried",
    "Dahi Ke Kabab | Hung curd kebabs, soft inside and crisp outside",
    "Dingree Ke Khass | Mushrooms stuffed and grilled with a house masala",
    "Tandoori Soya Tikka | Soya chunks marinated and grilled in the tandoor",
    "Kabuli Tikiya | Chickpea patties with Afghan-style spices",
    "Veg Galouti Kabab | Tender minced vegetable kebab",
    "Kashmiri Tikki | Potato tikki with Kashmiri spices",
    "Nawabi Aloo Kafta | Potato dumplings with a rich filling",
    "Chilly Garlic Mushroom | Mushrooms tossed with chilli and garlic",
    "Coastal BBQ Mushroom | Mushrooms barbecued with coastal spices",
    "Roasted Potato with Herbs | Potatoes roasted with herbs and butter",
    "Soya Tikki | Soya patties, shallow fried",
    "Veg Shami Kabab | Lentil and vegetable kebab",
    "Malai Soya Chaap | Soya chaap in a creamy marinade, grilled",
    // Kids snacks
    "French Fries | Crisp golden potato fries",
    "Chilli Garlic Potatoes | Potato wedges tossed with chilli and garlic",
    "Mushroom Cheese Shots | Mushroom and cheese bites, crumb fried",
    "Baby Corn Fritters | Baby corn in a light batter, fried",
    "Smileys | Smiley-shaped potato bites",
    "Nachos with Dip | Corn nachos served with salsa and cheese dip",
    "Mini Burger | Small veg burger with sauce and cheese",
    "Cheese Corn Sandwich | Toasted sandwich with corn and melted cheese",
    "Baby Vegetable Sandwich | Small vegetable sandwich",
    "Vada Pav | Spiced potato fritter in a soft pav",
    "Veg Puff | Flaky pastry with a spiced vegetable filling",
    "Masala Vada | Crunchy chana dal fritters",
    "Curd Vada | Soft lentil vada soaked in seasoned curd",
    "Onion Pakoda | Crisp onion fritters",
    "Veg Bonda | Spiced potato balls in a gram flour coating",
    "Bread Pakoda | Bread slices stuffed and fried in gram flour batter",
    "Aloo Bonda | Spiced potato dumplings in a besan crust",
    "Bajji | Vegetables dipped in gram flour batter and fried",
    "Baby Corn Rawa Fry | Baby corn coated in semolina and shallow fried",
    "Samosa | Crisp pastry filled with spiced potato and peas",
    "Kachori | Flaky fried pastry with a spiced lentil filling",
    "Dhokla | Steamed, spongy gram flour cakes",
  ]],
  ["Starters", N, [
    "Chicken Manchurian | Fried chicken in a tangy Manchurian sauce",
    "Peri Peri Chicken | Chicken grilled with fiery peri peri marinade",
    "Chicken Chilli | Chicken tossed with capsicum in spicy chilli sauce",
    "Fish Fingers | Crumb-coated fish strips, fried crisp",
    "Honey Chilli Chicken | Crispy chicken in a sweet and spicy glaze",
    "Noodles Wrapped Chicken | Chicken coated in crisp noodles",
    "Chicken Tikka | Boneless chicken marinated in spices and grilled",
    "Chicken Kebab | Spiced chicken kebab, grilled",
    "Thai Crispy Chicken | Crisp chicken with Thai-style sweet chilli sauce",
    "Chicken Nuggets | Crumb-coated chicken bites",
    "Fish Amritsari | Spiced gram flour battered fish, Amritsar style",
        "Chapli Kabab | Peshawari-style spiced minced meat kebab",
    "Chicken Boti Kabab | Chunks of chicken marinated and grilled",
    "Chicken Satay | Skewered chicken with a peanut dip",
    "Chilli Garlic Fish | Fish tossed with chilli and garlic",
    "Chilly Garlic Chicken | Chicken stir-fried with chilli and garlic",
    "Coastal BBQ Fish | Fish barbecued with coastal spices",
    "Murgh Malai Tikka | Creamy, mildly spiced chicken tikka",
    "Zafrani Murgh | Chicken marinated in saffron and cream",
    "Chicken Galouti Kebab | Melt-in-the-mouth minced chicken kebab",
    "Mutton Galouti Kebab | Tender minced mutton kebab",
    "Karachi Tangdi | Chicken drumsticks in a Karachi-style marinade",
    "Punjabi Tangdi | Chicken drumsticks in a Punjabi marinade",
    "Angara Tangdi | Chicken drumsticks in a smoky red marinade",
    "Peri Peri Tangdi | Chicken drumsticks in peri peri marinade",
    "Arabian Kafta Minced Patty | Minced meat patty with Arabian spices",
    "Mutton Seekh Kabab | Minced mutton kebab grilled on skewers",
    "Mutton Boti Kabab | Chunks of mutton marinated and grilled",
    "Azwaini Fish Tikka | Fish marinated with carom seeds and grilled",
    "Gurda Kaleji | Goat kidney and liver, spiced and pan roasted",
    "Kalmi Kabab | Chicken drumette marinated and grilled",
    "Mirch Masala Chicken Tikka | Spicy chicken tikka with chilli masala",
    "Murg Punjabi Tikka | Chicken tikka with Punjabi spices",
    "Kasuni Fish | Fish in a fenugreek-flavoured marinade",
    "Shikampuri Kabab | Minced meat kebab with a creamy filling",
    "Saufiyani Murgh Tikka | Chicken tikka flavoured with fennel",
    "Malai Chicken Kebab | Creamy chicken kebab",
    "Chicken Reshmi Kebab | Silky, cream-marinated chicken kebab",
    "Chicken Seekh Kebab | Minced chicken kebab on skewers",
    "Chicken 65 | Spicy fried chicken with curry leaves",
    "Pepper Chicken | Chicken tossed in crushed black pepper",
    "Andhra Chicken Fry | Spicy Andhra-style fried chicken",
    "Tandoori Fish | Fish marinated in spices and cooked in the tandoor",
    "Masala Omelette | Omelette with onion, chilli and coriander",
    "Cheese Omelette | Omelette filled with melted cheese",
    "Boiled Eggs | Plain boiled eggs",
    "Fried Eggs | Eggs fried to order",
    "Scrambled Eggs | Soft scrambled eggs",
  ]],
  ["Main Course", V, [
    // Paneer
    "Paneer Makhani | Paneer in a rich buttery tomato gravy",
    "Palak Paneer | Paneer in a smooth spinach gravy",
    "Shahi Paneer | Paneer in a creamy, mildly sweet cashew gravy",
    "Paneer Lababdar | Paneer in a rich onion tomato gravy",
    "Kadai Paneer | Paneer cooked with capsicum and ground kadai spices",
    "Matar Paneer | Paneer and green peas in a spiced tomato gravy",
    "Paneer Butter Masala | Paneer in a creamy tomato butter gravy",
    "Achari Paneer | Paneer cooked with pickling spices",
    "Paneer Kolhapuri | Spicy Kolhapuri-style paneer curry",
    "Paneer Kali Mirch | Paneer in a creamy gravy with black pepper",
    "Paneer Methi Malai | Paneer in a creamy fenugreek gravy",
    "Paneer Do Pyaza | Paneer cooked with onions in two ways",
    "Paneer Tikka Masala | Grilled paneer in a spiced tomato gravy",
    "Paneer Jalfrezi | Paneer stir-fried with vegetables in a tangy sauce",
    "Paneer Badshahi | Royal-style paneer in a rich creamy gravy",
    "Kadai Paneer Shashlik | Paneer and vegetable skewers served in kadai gravy",
    "Palak Paneer Razila | Paneer and spinach in a rich gravy",
    "Paneer Khurchan | Semi-dry paneer scraped and cooked with spices",
    "Malai Kofta Curry | Soft paneer and potato dumplings in a creamy gravy",
    // Veg
    "Mix Veg Dry | Mixed vegetables cooked dry with spices",
    "Aloo Gobi | Potato and cauliflower cooked dry with spices",
    "Aloo Jeera | Potatoes tempered with cumin",
    "Matar Mushroom | Mushrooms and green peas in a spiced gravy",
    "Makai Kumbh Palak | Corn and mushrooms in a spinach gravy",
    "Bhindi Masala | Okra cooked with onions and spices",
    "Sabji Jaipuri | Jaipur-style mixed vegetables",
    "Vegetables in Garlic Sauce | Mixed vegetables in a garlic sauce",
    "Mili Juli Sabji | Mixed vegetables in a semi-gravy",
    "Veg Kofta Curry | Vegetable dumplings in a rich gravy",
    "Bhindi Do Pyaza | Okra cooked with onions two ways",
    "Achari Bhindi | Okra cooked with pickle spices",
    "Bhindi Kurkure | Crispy fried okra tossed with spices",
    "Kadi Pakoda | Gram flour fritters in a tangy yogurt curry",
    "Dum Aloo | Baby potatoes slow cooked in a spiced gravy",
    "Subz Kofta in Palak Gravy | Vegetable dumplings in a spinach gravy",
    "Veg Khoorma | Vegetables in a mild creamy korma gravy",
    "Achari Vegetable | Vegetables cooked with pickling spices",
    "Methi Malai Matar | Green peas in a creamy fenugreek gravy",
    "Vegetable Kolhapuri | Mixed vegetables in a hot Kolhapuri masala",
    "Kadai Vegetable | Vegetables cooked in a spicy kadai masala",
    "Mushroom Masala | Mushrooms in a spiced onion tomato gravy",
    "Veg Jalfrezi | Vegetables stir-fried in a tangy tomato sauce",
    "Vegetable Makhani | Vegetables in a buttery tomato gravy",
    "Shahjahan Sabji | Vegetables in a rich Mughlai-style gravy",
    "Matar Mushroom Makhni | Mushrooms and peas in a buttery gravy",
    "Nargisi Kofta Curry | Egg-shaped vegetable kofta in a rich gravy",
    "Navratan Korma | Mixed vegetables, fruit and nuts in a creamy gravy",
    "Dum Aloo Kashmiri | Potatoes in a Kashmiri-style gravy",
    "Govind Gatta Curry | Gram flour dumplings in a spiced yogurt gravy",
    "Gutta Curry | Rajasthani gram flour dumplings in curry",
    "Mutter Mushroom Makhana | Mushrooms, peas and lotus seeds in gravy",
    "Corn Palak | Sweet corn in a spinach gravy",
    "Kaju Khoya Makhana Curry | Cashew, khoya and lotus seed curry",
    "Aloo Methi | Potatoes cooked with fenugreek leaves",
    "Aloo Hyderabadi | Hyderabadi-style spiced potatoes",
    "Bhindi Fry | Crisp fried okra",
    "Aloo Fry | Spiced fried potatoes",
    "Beans Palya | Karnataka-style beans stir-fried with coconut",
    "Potato Palya | South Indian spiced potato stir-fry",
    "Beans Cashew Palya | Beans stir-fried with cashews and coconut",
    "Thondekai Cashew Palya | Ivy gourd stir-fried with cashews",
    "Mix Veg Palya | Mixed vegetables stir-fried South Indian style",
    "Soppu Kalu Palya | Leafy greens and legumes stir-fry",
    "Chana Palya | Chickpeas stir-fried with coconut and spices",
    "Aloo Matar | Potato and green peas in a spiced gravy",
    "Veg Kurma | Mixed vegetables in a coconut-based kurma",
    "Chana Masala | Chickpeas in a tangy onion tomato gravy",
    "Yennegai | Baby aubergines in a rich peanut and tamarind gravy",
    "Sagu | Mixed vegetable curry with coconut and spices",
    "Amritsari Chole | Spiced chickpeas, Amritsar style",
    "Poori Aloo Matar | Fried poori served with potato and peas curry",
    "Poori Bhaji | Fried poori served with potato bhaji",
    "Chole Bhature | Spiced chickpeas served with fried bhatura",
  ]],
  ["Main Course", N, [
    "Butter Chicken | Tender chicken in a rich buttery tomato gravy",
    "Kadai Murgh | Chicken cooked with capsicum and freshly ground kadai spices",
    "Achari Murgh | Chicken cooked with pickling spices",
    "Murgh Afghani | Chicken in a creamy, mild Afghani-style gravy",
    "Murgh Hyderabadi | Chicken in a spiced Hyderabadi gravy",
    "Chicken Chettinad | Fiery Chettinad chicken with roasted spices",
    "Garlic Chicken | Chicken in a garlic-forward gravy",
    "Dum Ka Murgh | Chicken slow cooked on dum in a sealed pot",
    "Murgh Kolhapuri | Hot and spicy Kolhapuri-style chicken",
    "Chicken Lazeez | Chicken in a rich, flavourful house gravy",
    "Murgh Peshawari | Chicken in a Peshawari-style gravy",
    "Murgh Patiyala | Patiala-style chicken in a thick gravy",
    "Fish Curry | Fish in a tangy coastal-style curry",
    "Fish Gashi | Fish in a coconut-based Mangalorean gravy",
    "Egg Masala | Boiled eggs in a spiced onion tomato gravy",
    "Burrani Ghosht | Mutton cooked in a spiced yogurt gravy",
    "Chicken Korma | Chicken in a creamy, mildly spiced gravy",
    "Dhaba Gosht | Rustic dhaba-style mutton curry",
    "Laal Maas | Fiery Rajasthani red mutton curry",
    "Chicken Curry | Home-style chicken curry",
    "Murgh Do Pyaza | Chicken cooked with onions in two ways",
    "Dhania Murg | Chicken in a fresh coriander gravy",
    "Murg Wajid Ali | Chicken in a rich Awadhi-style gravy",
    "Murgh Begmati | Chicken in a royal Begum-style gravy",
    "Murgh Saagwala | Chicken in a spinach gravy",
    "Mutton Korma | Mutton in a creamy, mildly spiced gravy",
    "Mutton Curry | Home-style mutton curry",
    "Nahari Ghosht | Slow-cooked mutton in a rich spiced gravy",
    "Mutton Rogan Josh | Kashmiri-style mutton in an aromatic red gravy",
    "Chicken Tikka Masala | Grilled chicken in a spiced tomato gravy",
    "Murg Lababdar | Chicken in a rich onion tomato gravy",
    "Chicken Kadai | Chicken cooked in a spicy kadai masala",
  ]],
  ["Main Course", V, [
    "Dal Tadka | Yellow lentils tempered with garlic and cumin",
    "Dal Panchrangi | Five-lentil dal with a spiced tempering",
    "Dal Palak | Lentils cooked with spinach",
    "Dal Bukhara | Slow-cooked black lentils in a rich creamy gravy",
    "Dal Makhani | Black lentils and kidney beans simmered with butter and cream",
    "Masoor Dal Fry | Red lentils fried with onion and spices",
    "Dal Kolhapuri | Spicy Kolhapuri-style lentils",
    "Dal Amritsari | Amritsar-style creamy lentils",
    "Methi Dal Tadka | Tempered lentils with fenugreek leaves",
    "Rajma Masala | Kidney beans in a spiced onion tomato gravy",
    "Dal Panchmel | Five-lentil dal, Rajasthani style",
    "Special Sambar | South Indian lentil and vegetable stew",
    "Rasam | Peppery tamarind and tomato broth",
    "Pav Bhaji | Spiced mashed vegetable curry served with buttered pav",
    "Noodles Manchurian | Noodles tossed in a Manchurian sauce",
    "Sweet & Sour Vegetables | Vegetables in a sweet and sour sauce",
    "Mix Vegetable in Hot Garlic Sauce | Vegetables in a spicy garlic sauce",
    "Salt & Pepper Vegetables | Crisp vegetables tossed with salt and pepper",
    "Honey Chilli Cauliflower | Crisp cauliflower in a honey chilli glaze",
    "Broccoli Baby Corn Mushroom in Soya Chilli Sauce | Vegetables tossed in a soya chilli sauce",
    "Vegetable Balls Manchurian | Vegetable balls in a Manchurian gravy",
    "Vegetable Chopsuey | Crispy noodles topped with vegetables in a sauce",
    "Veg Fried Noodles | Wok-tossed noodles with vegetables",
    "Singapore Fried Noodles | Curry-spiced noodles with vegetables",
    "Chilly Garlic Noodles | Noodles tossed with chilli and garlic",
    "Penne Pasta | Penne in tomato basil or cheese cream sauce, with exotic vegetables",
    "Pesto Pasta | Pasta tossed in basil pesto with vegetables",
  ]],
  ["Rice & Biryani", V, [
    "Veg Biryani | Fragrant basmati rice layered with spiced vegetables",
    "Veg Pulao | Basmati rice cooked with vegetables and whole spices",
    "Veg Fried Rice | Wok-tossed rice with vegetables",
    "Jeera Pulao | Pulao flavoured with cumin and ghee",
    "Green Peas Pulao | Basmati rice cooked with green peas",
    "Hyderabadi Biryani | Dum-cooked vegetable biryani, Hyderabad style",
    "Jeera Rice | Basmati rice tempered with cumin",
    "Steamed Rice | Plain steamed basmati rice",
    "Kaju Kishmish Pulao | Pulao with cashews and raisins",
    "Veg Andhra Pulao | Spicy Andhra-style vegetable pulao",
    "Murshidabadi Veg Dum Biryani | Slow-cooked vegetable biryani, Murshidabad style",
    "Dry Fruit Pulao | Rich pulao with mixed dry fruits",
    "Jodhpuri Pulao | Rajasthani-style pulao",
    "Corn Pulao | Basmati rice cooked with sweet corn",
    "Kashmiri Pulao | Mildly sweet pulao with dry fruits and saffron",
    "Curd Rice | Soft rice mixed with seasoned yogurt",
    "Green Peas and Cashew Pulao | Pulao with green peas and cashews",
    "Mushroom Biryani | Dum-cooked biryani with mushrooms",
    "Paneer Peas Pulao | Pulao with paneer and green peas",
    "Ghee Rice | Rice cooked in ghee with whole spices",
    "Vangi Bath | Karnataka brinjal rice with a spice blend",
    "Bisibele Bath | Spicy rice and lentil dish with vegetables",
    "Singapore Fried Rice | Curry-spiced fried rice with vegetables",
  ]],
  ["Rice & Biryani", N, [
    "Chicken Dum Biryani | Basmati rice and chicken slow cooked on dum",
    "Chicken Fried Rice | Wok-tossed rice with chicken",
    "Chicken Natti Biryani | Country-style chicken biryani",
    "Chicken Popcorn Biryani | Biryani topped with crispy chicken popcorn",
    "Chicken Hyderabadi Biryani | Chicken biryani, Hyderabad style",
    "Egg Fried Rice | Wok-tossed rice with scrambled egg",
  ]],
  ["Breads", V, [
    "Plain Paratha | Layered whole wheat flatbread cooked on a tawa",
    "Phulka | Soft puffed whole wheat flatbread",
    "Roti | Whole wheat flatbread cooked on a tawa",
    "Poori | Deep-fried puffed bread",
    "Bhatura | Soft, fluffy deep-fried bread",
    "Stuffed Poori | Deep-fried bread with a spiced filling",
    "Naan | Soft tandoor-baked bread",
    "Butter Naan | Tandoor naan brushed with butter",
    "Stuffed Naan | Naan filled with a spiced stuffing",
    "Tandoori Roti | Whole wheat bread baked in the tandoor",
    "Kulcha | Soft leavened tandoor bread",
    "Onion Kulcha | Kulcha stuffed with spiced onion",
    "Aloo Kulcha | Kulcha stuffed with spiced potato",
    "Mix Kulcha | Kulcha stuffed with mixed vegetables",
    "Rumali Roti | Thin handkerchief-style flatbread",
    "Palak Poori | Spinach-flavoured fried bread",
    "Lacha Paratha | Flaky, multi-layered paratha",
    "Methi Paratha | Paratha flavoured with fenugreek leaves",
    "Chapathi | Soft whole wheat flatbread",
    "Akki Roti | Karnataka rice flour flatbread",
    "Missi Roti | Gram flour and wheat flatbread",
    "Khasta Roti | Crisp, flaky tandoor roti",
    "Butter Phulka | Phulka brushed with butter",
  ]],
  ["Salads & Accompaniments", V, [
    "Garden Green Salad | Fresh seasonal vegetables",
    "Green Salad | Cucumber, tomato, onion and carrot",
    "Greek Salad | Cucumber, olives, tomato and feta with herb dressing",
    "Caesar Salad (Veg) | Lettuce, croutons and Parmesan with Caesar dressing",
    "Russian Salad | Mixed vegetables and fruit in a creamy dressing",
    "Sprout Salad | Fresh mixed sprouts with onion, tomato and lemon",
    "Pasta Salad | Pasta with vegetables in a light dressing",
    "Corn & Bean Salad | Sweet corn and beans with herbs",
    "Corn Salad | Sweet corn tossed with herbs and lemon",
    "Coleslaw Salad | Shredded cabbage and carrot in creamy dressing",
    "Kimchi Salad | Tangy, spicy fermented-style cabbage salad",
    "Aloo Chana Chaat Salad | Potato and chickpea salad with chaat spices",
    "Kosumbari Salad | Lentil and cucumber salad with coconut",
    "Cold Cucumber Salad | Chilled cucumber with a light dressing",
    "Watermelon and Feta Salad | Watermelon with feta cheese and mint",
    "Fresh Salad Bar | Fresh vegetables, toppings and dressings to build your own salad",
    "Fruit Kosambari | Fruit and soaked lentil salad",
    "Peanut Kosambari | Peanut and cucumber salad",
    "Sprout Kosambari | Sprouted lentil salad",
    "Moong Dal Kosambari | Soaked moong dal salad with coconut",
    "Hesaru Bele Kosumbari | Soaked moong dal salad, Karnataka style",
    "Molake Kalu Kosumbari | Sprouted bean salad, Karnataka style",
    "Corn Kosumbari | Sweet corn salad, Karnataka style",
    "Papad | Crisp roasted or fried lentil wafers",
    "Pickle | Traditional spiced Indian pickle",
    "Pudina Chutney | Fresh mint chutney",
    "Raita | Whisked yogurt with cucumber or boondi",
    "Boondi Raita | Yogurt with crisp gram flour pearls",
    "Plain Curd | Fresh set yogurt",
    "Coconut Chutney | Fresh coconut chutney",
    "Cut Fruit | Seasonal fresh cut fruit",
    "Fruit Platter | Seasonal and exotic fruit platter",
  ]],
  ["Desserts", V, [
    "Gulab Jamun | Soft milk dumplings soaked in rose-scented syrup",
    "Kala Jamun | Dark, rich fried milk dumplings in syrup",
    "Rasmalai | Soft cheese patties in chilled saffron milk",
    "Rasgulla | Spongy cheese balls in light sugar syrup",
    "Gajar Ka Halwa | Slow-cooked carrot halwa with ghee and nuts",
    "Beetroot Halwa | Slow-cooked beetroot halwa with ghee",
    "Moong Dal Halwa | Rich lentil halwa cooked in ghee",
    "Fruit Salad | Seasonal fresh fruit salad",
    "Shahi Thukda | Fried bread soaked in sweet saffron rabri",
    "Rice Kheer | Creamy rice pudding with cardamom",
    "Fruit Custard | Chilled custard with fresh fruit",
    "Chocolate Pastry | Layered chocolate cake slice",
    "Pineapple Pastry | Pineapple cream cake slice",
    "Brownie | Dense chocolate brownie",
    "Brownie with Ice Cream | Warm brownie served with ice cream",
    "Green Pumpkin Halwa | Ash gourd halwa with ghee and nuts",
    "Pumpkin Kheer | Creamy pumpkin pudding",
    "Semiya Payasam | Vermicelli pudding in sweet milk",
    "Payasam | South Indian milk-based pudding",
    "Rabdi | Thickened sweetened milk with nuts",
    "Dry Fruit Kheer | Milk pudding with mixed dry fruits",
    "Cham Cham | Soft Bengali cheese sweet",
    "Champakali | Cheese sweet with a creamy filling",
    "Malai Sandwich | Creamy milk sweet sandwich",
    "Phirni | Chilled ground rice pudding",
    "Dry Jamun | Fried milk dumplings rolled in sugar",
    "Angoori Jamun | Tiny grape-sized gulab jamun",
    "Fruit Kebab | Fruit skewers",
    "Moti Rasmalai | Pearl-sized rasmalai",
    "Cup Cake | Soft frosted cup cake",
    "Swiss Roll | Soft sponge rolled with cream",
    "Live Malpua with Rabri | Hot fried pancakes served with rabri",
    "Live Jalebi with Rabri | Hot crisp jalebi served with rabri",
    "Kashi Halwa | Ash gourd halwa, South Indian style",
    "Holige | Sweet flatbread stuffed with lentils and jaggery",
    "Chiroti | Flaky layered sweet",
    "Pheni | Fine crisp vermicelli sweet served with milk",
    "Mysore Pak | Rich ghee and gram flour sweet",
    "Motichur Laddu | Fine boondi laddu",
    "Badusha | Flaky, syrup-glazed sweet",
    "Badam Puri | Almond-stuffed sweet puri",
    "Chandrakala | Crescent-shaped sweet with a creamy filling",
    "Jalebi | Crisp spirals soaked in sugar syrup",
    "Glass Sandwich | Layered sweet served in a glass",
    "Suji Halwa | Semolina halwa with ghee",
    "Vanilla Ice Cream | Classic vanilla ice cream",
    "Chocolate Ice Cream | Rich chocolate ice cream",
    "Butterscotch Ice Cream | Butterscotch ice cream with caramel crunch",
    "Strawberry Ice Cream | Strawberry ice cream",
    "Pista Ice Cream | Pistachio ice cream",
    "Mango Ice Cream | Mango ice cream",
    "Chikoo Ice Cream | Sapota ice cream",
    "Kaju Malai Ice Cream | Cashew and cream ice cream",
    "Arabian Delight Ice Cream | Ice cream with dates, nuts and spices",
    "Fruit Punch Ice Cream | Mixed fruit ice cream",
    "Tilla Wali Kulfi | Kulfi topped with dry fruit",
    "Dry Fruit Kulfi | Kulfi with mixed dry fruit",
    "Malai Kulfi | Creamy traditional kulfi",
    "Chocolate Fountain | Flowing melted chocolate with dippers",
    "Cotton Candy | Spun sugar candy",
    "Ice Gola | Shaved ice with flavoured syrup",
  ]],
  ["Breakfast", V, [
    "Idli | Soft steamed rice and lentil cakes",
    "Mini Idli | Bite-size idlis with chutney",
    "Vada | Crisp South Indian lentil doughnut",
    "Poori Sagu | Fried poori served with vegetable sagu",
    "Masala Dosa | Crisp dosa filled with spiced potato",
    "Set Dosa | Soft, spongy dosas served in sets",
    "Podi Dosa | Dosa spread with spicy lentil powder",
    "Plain Dosa | Thin crisp rice and lentil crepe",
    "Ghee Upma | Semolina cooked with ghee and vegetables",
    "Vegetable Upma | Semolina cooked with vegetables",
    "Semiya Upma | Vermicelli cooked with vegetables and spices",
    "Pongal | Rice and moong dal cooked with pepper, cumin and ghee",
    "Kesaribath | Sweet semolina dish with saffron",
    "Pineapple Kesaribath | Sweet semolina dish with pineapple",
    "Poha | Flattened rice cooked with onion, peanuts and spices",
    "Indori Poha | Madhya Pradesh style poha with sev and lemon",
    "Upma | Savoury semolina breakfast dish",
    "Cheela | Savoury gram flour pancake",
    "Moong Dal Stuffed Cheela | Lentil pancake with a savoury filling",
    "Aloo Paratha | Paratha stuffed with spiced potato",
    "Paneer Paratha | Paratha stuffed with spiced paneer",
    "Gobi Paratha | Paratha stuffed with spiced cauliflower",
    "Bedmi Poori with Aloo Sabzi | Spiced lentil poori served with potato curry",
    "Sandwich | Sandwich served cold, buttered or with jam",
    "Mini Croissants | Buttery bite-size croissants",
    "Danish Pastries | Flaky fruit or cream pastries",
    "Corn Flakes with Milk | Corn flakes served with cold or hot milk",
    "Garlic Bread | Toasted bread with garlic butter",
    "Toast with Butter | Toasted bread with butter",
    "Muffins | Soft baked muffins",
    "Appam with Veg Stew | Lacy rice hoppers with a mild vegetable stew",
    "Paddu | Fluffy rice and lentil dumplings served with chutney",
    "Pesarattu | Green gram dosa",
    "Pancakes with Maple Syrup | Soft pancakes with maple syrup",
  ]],
  ["Live Counters", V, [
    "Gol Gappe | Crisp hollow puris with tangy flavoured water",
    "Bhalla Papri | Lentil dumplings with papri, yogurt and chutneys",
    "Dahi Poori | Crisp puris filled with yogurt and chutneys",
    "Palak Patta Chaat | Crisp spinach leaves topped with yogurt and chutneys",
    "Dahi Papri Chaat | Crisp papri with yogurt and chutneys",
    "Sev Puri | Crisp puris topped with potato, sev and chutneys",
    "Bhel Puri | Puffed rice tossed with onion, tomato and chutneys",
    "Raj Kachori | Large crisp kachori filled with yogurt and chutneys",
    "Aloo Tikki Chaat | Potato patties topped with yogurt and chutneys",
    "Dabeli | Spiced potato filling in a bun with peanuts and chutney",
    "Masala Puri | Crushed puris topped with spiced gravy",
    "Momos | Steamed or fried vegetable dumplings with spicy chutney",
    "Loaded Nachos | Nachos with dressings and toppings",
    "Family Tawa | Assorted vegetables cooked live on the tawa",
    "Assorted Fries | Salted and peri peri fries",
    "Paan | Plain, meetha or chocolate paan",
    "Popcorn | Freshly popped popcorn",
    "Pizza | Freshly baked vegetable pizza",
    "Waffles | Fresh waffles with toppings",
    "Tandoor Live Counter | Roti, naan and kulcha made fresh in the tandoor",
  ]],
];

export const CATALOG_SEED: CatalogSeed[] = SECTIONS.flatMap(([categoryName, foodType, lines]) =>
  lines.map((line) => {
    const [name, description] = line.split(" | ");
    return { name: name.trim(), description: description.trim(), foodType, categoryName };
  }),
);
