/**
 * Photos for Platterly's master catalog (2026-10-10): openly licensed pictures from Wikimedia Commons, resized to
 * 800x450 WebP under public/catalog/photos. Every other dish shows its category illustration (public/catalog/categories).
 * Pure data with no imports, so the seed script can load it. Credits are also listed in public/catalog/photos/CREDITS.md.
 */
export const CATALOG_PHOTOS: Record<string, { photo: string; credit: string; source: string }> = {
  "Jal Jeera": { photo: "jal-jeera.webp", credit: "Rutvi Mistry, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Jal_jeera.jpg" },
  "Mojito": { photo: "mojito.webp", credit: "Pratishkhedekar, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Virgin_Mojito_02.jpg" },
  "Watermelon Juice": { photo: "watermelon-juice.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Watermelon_Juice_1.jpg" },
  "Sweet Lime Juice": { photo: "sweet-lime-juice.webp", credit: "No machine-readable author provided. Ranveig assumed (based on copyright claims)., Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Sweet_lime_and_pomegranate_juice.jpg" },
  "Aam Panna": { photo: "aam-panna.webp", credit: "Mdsmds0, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aam_Panna_(Raw_Mango_Drink).JPG" },
  "Tea": { photo: "tea.webp", credit: "Jubair1985, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Red_Tea.jpg" },
  "Black Tea": { photo: "black-tea.webp", credit: "Ultratomio, Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Black-tea.jpg" },
  "Green Tea": { photo: "green-tea.webp", credit: "Kanko* from Nagasaki, Japan, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Green_tea_-_%E7%B7%91%E8%8C%B6_-_Flickr_-_Kanko.jpg" },
  "Cream of Tomato Soup": { photo: "cream-of-tomato-soup.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Cream_of_Tomato_Soup.JPG" },
  "Hot & Sour Soup": { photo: "hot-and-sour-soup.webp", credit: "Evan-Amos, Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hot-and-Sour-Soup-Bowl.jpg" },
  "Minestrone Soup": { photo: "minestrone-soup.webp", credit: "Katrin Morenz from Aachen, Deutschland, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Minestrone_soup.jpg" },
  "Manchow Soup": { photo: "manchow-soup.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Manchow_soup.jpg" },
  "Lemon Coriander Soup": { photo: "lemon-coriander-soup.webp", credit: "Harikrishnan N, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Lemon_Chilli_Coriander_Soup_-_The_Asian_Curry_House,_Bangalore_-_Karnataka_-_PXL2005.jpg" },
  "Tomato Shorba": { photo: "tomato-shorba.webp", credit: "Radhikamprabhu82, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Tomato_Shorba(soup).jpg" },
  "Mulligatawny Soup": { photo: "mulligatawny-soup.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mulligatawny_Soup_(Pepper_Water_Soup).JPG" },
  "Cream of Mushroom Soup": { photo: "cream-of-mushroom-soup.webp", credit: "Redeemer|Vodesnet, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Cream_Mushroom_soup_2.jpg" },
  "Tomato Soup": { photo: "tomato-soup.webp", credit: "Unknown author, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Tomato_soup.jpg" },
  "Broccoli Soup": { photo: "broccoli-soup.webp", credit: "ParentingPatch, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Broccoli_Soup.JPG" },
  "Roasted Pumpkin Soup": { photo: "roasted-pumpkin-soup.webp", credit: "photonome, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pumpkin_soup_with_ginger_and_roasted_pumpkin_seeds.jpg" },
  "Sweet Corn Chicken Soup": { photo: "sweet-corn-chicken-soup.webp", credit: "Thamizhpparithi Maari, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_sweet_corn_soup.jpg" },
  "Hot & Sour Chicken Soup": { photo: "hot-and-sour-chicken-soup.webp", credit: "Sunshinegal10, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hot_n_Sour_Chicken_Soup.jpg" },
  "Paneer Malai Tikka": { photo: "paneer-malai-tikka.webp", credit: "Saakshi Salgaonker, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Malai_Tikka.jpg" },
  "Paneer Tikka": { photo: "paneer-tikka.webp", credit: "Srikoundinya66, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_tikka_1.jpg" },
  "Paneer Manchurian": { photo: "paneer-manchurian.webp", credit: "Sangam321, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Manchurian.jpg" },
  "Paneer Chilli": { photo: "paneer-chilli.webp", credit: "Gpkp, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Chilli,_Bengaluru_(2026)_02.jpg" },
  "Crispy Corn": { photo: "crispy-corn.webp", credit: "Dikshita Bairagi, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Crispy_chilli_baby_corn.....jpg" },
  "Honey Chilli Potato": { photo: "honey-chilli-potato.webp", credit: "Gannu03, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Honey_chilli_potato_2.jpg" },
  "Hara Bhara Kabab": { photo: "hara-bhara-kabab.webp", credit: "Kanikatwl, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hara_bhara_kabab-.JPG" },
  "Veg Cutlet": { photo: "veg-cutlet.webp", credit: "NEHAL NAZIM, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:VEG_CUTLETS.jpg" },
  "Baby Corn Golden Fry": { photo: "baby-corn-golden-fry.webp", credit: "Gowthydaas, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Golden_fry_baby_corn.jpg" },
  "Veg Spring Roll": { photo: "veg-spring-roll.webp", credit: "YKanchan07, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_spring_roll.jpg" },
  "Cheese Balls": { photo: "cheese-balls.webp", credit: "Sushant savla, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Cheese_Balls_-_1.jpg" },
  "Veg Lollipop": { photo: "veg-lollipop.webp", credit: "SS Khurana, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:VEG_LOLLIPOP.jpg" },
  "Gobi Manchurian": { photo: "gobi-manchurian.webp", credit: "scaredy_kat, CC BY 2.5, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Gobi_manchurian.jpg" },
  "Baby Corn Manchurian": { photo: "baby-corn-manchurian.webp", credit: "Sangam321, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Baby_Corn_Manchurian.jpg" },
  "Mushroom Manchurian": { photo: "mushroom-manchurian.webp", credit: "Anuradhayeluri, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mushroom_Manchurian_dry.jpg" },
  "Gobi Chilli": { photo: "gobi-chilli.webp", credit: "Gannu03, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chilli_gobi_2.jpg" },
  "Baby Corn Chilli": { photo: "baby-corn-chilli.webp", credit: "Keerthiga, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Baby_Corn_Chilli.jpg" },
  "Stuffed Mushroom": { photo: "stuffed-mushroom.webp", credit: "Crisco 1492, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Stuffed_mushrooms,_2015-06-25.jpg" },
  "Veg Seekh Kebab": { photo: "veg-seekh-kebab.webp", credit: "Meghana Mohanty, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_Seekh_kebab.jpg" },
  "Dahi Ke Kabab": { photo: "dahi-ke-kabab.webp", credit: "Ojaswani gupta, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dahi_ke_Kabab.jpg" },
  "French Fries": { photo: "french-fries.webp", credit: "StockSnap, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:French_Fries.JPG" },
  "Nachos with Dip": { photo: "nachos-with-dip.webp", credit: "Aerous, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Nachos_with_dip.jpg" },
  "Cheese Corn Sandwich": { photo: "cheese-corn-sandwich.webp", credit: "Photosticlife, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Corn_cheese_Sandwich.jpg" },
  "Vada Pav": { photo: "vada-pav.webp", credit: "Marajozkee, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Vada_pav_01.jpg" },
  "Masala Vada": { photo: "masala-vada.webp", credit: "Turbo1232112321, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Masala_vada_02.JPG" },
  "Onion Pakoda": { photo: "onion-pakoda.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Onion_Pakoda_1.jpg" },
  "Bread Pakoda": { photo: "bread-pakoda.webp", credit: "Prateek Pattanaik, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bread_Pakoda_2.jpg" },
  "Aloo Bonda": { photo: "aloo-bonda.webp", credit: "Iamalwayshungrie, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_bonda_2.jpg" },
  "Bajji": { photo: "bajji.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Onion_Bajji.jpg" },
  "Samosa": { photo: "samosa.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Samosa_4.jpg" },
  "Kachori": { photo: "kachori.webp", credit: "Rajeeb Dutta, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kachori_MA23.jpg" },
  "Dhokla": { photo: "dhokla.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dhokla_6.jpg" },
  "Chicken Manchurian": { photo: "chicken-manchurian.webp", credit: "Abhinaba Basu from Redmond, United States, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Manchurian_(Hyderabad_Style)_(11960049916).jpg" },
  "Peri Peri Chicken": { photo: "peri-peri-chicken.webp", credit: "CNEcija12345, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Peri-Peri_Chicken_dish.jpg" },
  "Chicken Chilli": { photo: "chicken-chilli.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Chilli_1.jpg" },
  "Honey Chilli Chicken": { photo: "honey-chilli-chicken.webp", credit: "MDRX, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Honey_Chilli_Chicken.jpg" },
  "Chicken Tikka": { photo: "chicken-tikka.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Tikka_1.jpg" },
  "Chicken Kebab": { photo: "chicken-kebab.webp", credit: "P1898, CC BY 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Hariyali_kebab.jpg" },
  "Fish Amritsari": { photo: "fish-amritsari.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Amritsari_Fried_Fish.JPG" },
  "Chapli Kabab": { photo: "chapli-kabab.webp", credit: "Miansari66, Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chapli_Kabab.JPG" },
  "Chicken Satay": { photo: "chicken-satay.webp", credit: "Elly Suhailee, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:CHICKEN_SATAY.jpg" },
  "Chilly Garlic Chicken": { photo: "chilly-garlic-chicken.webp", credit: "Yummy O Yummy, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Garlic_and_Kashmiri_Chilly_Chicken_(15727276038).jpg" },
  "Mutton Seekh Kabab": { photo: "mutton-seekh-kabab.webp", credit: "Dheerajk88, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mutton_Seekh_Kabab.JPG" },
  "Gurda Kaleji": { photo: "gurda-kaleji.webp", credit: "Syedandy, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Gurda_kaleji.jpg" },
  "Kalmi Kabab": { photo: "kalmi-kabab.webp", credit: "Harsha K R from Bangalore, India, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kalmi_Kabab_(3150331866).jpg" },
  "Shikampuri Kabab": { photo: "shikampuri-kabab.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Shikampuri_Kabab.JPG" },
  "Malai Chicken Kebab": { photo: "malai-chicken-kebab.webp", credit: "Ranjith Kumar, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Malai_Kebab.JPG" },
  "Chicken Reshmi Kebab": { photo: "chicken-reshmi-kebab.webp", credit: "Prianxi, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_reshmi_kebabs.jpg" },
  "Chicken Seekh Kebab": { photo: "chicken-seekh-kebab.webp", credit: "Ishitadsa, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Indian_Chicken_Seekh_Kebab.jpg" },
  "Chicken 65": { photo: "chicken-65.webp", credit: "Amiyashrivastava, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_65_(Dish).jpg" },
  "Andhra Chicken Fry": { photo: "andhra-chicken-fry.webp", credit: "Karteeki4u, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Andhra_chicken_fry.jpg" },
  "Tandoori Fish": { photo: "tandoori-fish.webp", credit: "Tinu alby, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Tandoori_fish.jpg" },
  "Masala Omelette": { photo: "masala-omelette.webp", credit: "SwingingUvula, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Masala_omelette.JPG" },
  "Boiled Eggs": { photo: "boiled-eggs.webp", credit: "Ramesh NG, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Boiled_Egg_-_Crossection.jpg" },
  "Fried Eggs": { photo: "fried-eggs.webp", credit: "Balise42, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Two_fried_eggs.jpg" },
  "Paneer Makhani": { photo: "paneer-makhani.webp", credit: "Divya Kudua, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Makhani_India_August_2013.jpg" },
  "Palak Paneer": { photo: "palak-paneer.webp", credit: "DreamyFlutura11, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Palak_Paneer_(Cottage_cheese_in_spinach_gravy).jpg" },
  "Shahi Paneer": { photo: "shahi-paneer.webp", credit: "Realanant 1995, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Naan_shahi_paneer.jpg" },
  "Paneer Lababdar": { photo: "paneer-lababdar.webp", credit: "Tarundahiya89, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_tikka_lababdar.JPG" },
  "Kadai Paneer": { photo: "kadai-paneer.webp", credit: "Yummy O Yummy, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kadai_Paneer_(15913018051).jpg" },
  "Matar Paneer": { photo: "matar-paneer.webp", credit: "Mdsmds0, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Matar-Paneer.JPG" },
  "Paneer Butter Masala": { photo: "paneer-butter-masala.webp", credit: "Gannu03, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_butter_masala_2.jpg" },
  "Achari Paneer": { photo: "achari-paneer.webp", credit: "Anwasha12, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Achari_paneer.JPG" },
  "Paneer Methi Malai": { photo: "paneer-methi-malai.webp", credit: "1Bongfoodie, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Methi_Paneer_Malai.jpg" },
  "Paneer Tikka Masala": { photo: "paneer-tikka-masala.webp", credit: "Gpkp, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Tikka_Masala_(2026)_01.jpg" },
  "Paneer Jalfrezi": { photo: "paneer-jalfrezi.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Jalfrezi_2.jpg" },
  "Paneer Khurchan": { photo: "paneer-khurchan.webp", credit: "Saishalini7, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Khurchan.JPG" },
  "Malai Kofta Curry": { photo: "malai-kofta-curry.webp", credit: "Mrudit161187, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Malai_Kofta_Curry.jpg" },
  "Mix Veg Dry": { photo: "mix-veg-dry.webp", credit: "Sattwik03, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mix_veg_Bhaja.jpg" },
  "Aloo Gobi": { photo: "aloo-gobi.webp", credit: "Unknown author, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_gobi.jpg" },
  "Aloo Jeera": { photo: "aloo-jeera.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Jeera_aloo.jpg" },
  "Matar Mushroom": { photo: "matar-mushroom.webp", credit: "Hrishikes, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Matar_mushroom.jpg" },
  "Bhindi Masala": { photo: "bhindi-masala.webp", credit: "Monali.mishra, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bhindi_Masala.jpg" },
  "Kadi Pakoda": { photo: "kadi-pakoda.webp", credit: "Fatimahope, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kadi_pakoda.jpg" },
  "Dum Aloo": { photo: "dum-aloo.webp", credit: "Mrudit161187, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dum_Aloo_Kashmiri.jpg" },
  "Methi Malai Matar": { photo: "methi-malai-matar.webp", credit: "Ujjawaoo7, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Methi_Malai_Matar.jpg" },
  "Veg Jalfrezi": { photo: "veg-jalfrezi.webp", credit: "Fatfoodie, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_Jalfrezi.jpg" },
  "Navratan Korma": { photo: "navratan-korma.webp", credit: "User:Augustgrahl, Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Navratan_Korma.jpg" },
  "Dum Aloo Kashmiri": { photo: "dum-aloo-kashmiri.webp", credit: "Mrudit161187, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dum_Aloo_Kashmiri.jpg" },
  "Corn Palak": { photo: "corn-palak.webp", credit: "Kanikatwl, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Corn_spinach-_makai_malai_palak.JPG" },
  "Aloo Methi": { photo: "aloo-methi.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_Methi_(Aaloo_Methi).JPG" },
  "Bhindi Fry": { photo: "bhindi-fry.webp", credit: "Joli Rumi, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bhindi_fry.jpg" },
  "Aloo Matar": { photo: "aloo-matar.webp", credit: "Zeel Patel, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_Matar.JPG" },
  "Poori Bhaji": { photo: "poori-bhaji.webp", credit: "Kanikatwl, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Poori_bhaji.jpg" },
  "Chole Bhature": { photo: "chole-bhature.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chole_Bhature_1.jpg" },
  "Butter Chicken": { photo: "butter-chicken.webp", credit: "Mack Male from Edmonton, AB, Canada, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Butter_Chicken_(2446546141).jpg" },
  "Kadai Murgh": { photo: "kadai-murgh.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kadai_Murgh.jpg" },
  "Chicken Chettinad": { photo: "chicken-chettinad.webp", credit: "Shashank7200, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Chettinad_02.JPG" },
  "Dum Ka Murgh": { photo: "dum-ka-murgh.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dum_ka_Murgh.jpg" },
  "Fish Curry": { photo: "fish-curry.webp", credit: "Solomon The Magnifico, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bangladeshi_Fish_Curry_Rice.jpg" },
  "Egg Masala": { photo: "egg-masala.webp", credit: "வெங்கட்ராமன். தி, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chettinad_Egg_masala.jpg" },
  "Chicken Korma": { photo: "chicken-korma.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Korma.JPG" },
  "Chicken Curry": { photo: "chicken-curry.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Curry_9.jpg" },
  "Mutton Korma": { photo: "mutton-korma.webp", credit: "Sharnab neogi, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mutton_Korma_(Indian).jpg" },
  "Mutton Curry": { photo: "mutton-curry.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mutton_Curry_(44786).jpg" },
  "Mutton Rogan Josh": { photo: "mutton-rogan-josh.webp", credit: "stu_spivack, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mutton_rogan_josh.jpg" },
  "Chicken Tikka Masala": { photo: "chicken-tikka-masala.webp", credit: "Michael Hays, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_tikka_masala.jpg" },
  "Chicken Kadai": { photo: "chicken-kadai.webp", credit: "Keerthi93, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kadai_chicken.jpg" },
  "Dal Tadka": { photo: "dal-tadka.webp", credit: "Southofindia, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Tadka_Dal.jpg" },
  "Dal Palak": { photo: "dal-palak.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dal_Palak.jpg" },
  "Dal Bukhara": { photo: "dal-bukhara.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dal_Bukhara.JPG" },
  "Dal Makhani": { photo: "dal-makhani.webp", credit: "Charles Haynes, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dal_Makhani.jpg" },
  "Rajma Masala": { photo: "rajma-masala.webp", credit: "Gaurav Nemade, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Rajma_Masala_(32081557778).jpg" },
  "Special Sambar": { photo: "special-sambar.webp", credit: "Kalaiselvi Murugesan, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pumpkin_sambar.JPG" },
  "Rasam": { photo: "rasam.webp", credit: "Miansari66, Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Rasam.JPG" },
  "Pav Bhaji": { photo: "pav-bhaji.webp", credit: "Rishika Palvankar, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pav_Bhaji.jpg" },
  "Noodles Manchurian": { photo: "noodles-manchurian.webp", credit: "PallaviKhale, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hakka_Noodles,_Veg_Manchurian_PK009.jpg" },
  "Honey Chilli Cauliflower": { photo: "honey-chilli-cauliflower.webp", credit: "Harmeet, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Honey_chilli_cauliflower.jpg" },
  "Singapore Fried Noodles": { photo: "singapore-fried-noodles.webp", credit: "Andy Li, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Singapore_Fried_Noodles_-_Unithai_2025-05-07.jpg" },
  "Veg Pulao": { photo: "veg-pulao.webp", credit: "Sumit Surai, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_Pulao_(Indian_fried_rice).jpg" },
  "Veg Fried Rice": { photo: "veg-fried-rice.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_Fried_Rice_(51465).jpg" },
  "Hyderabadi Biryani": { photo: "hyderabadi-biryani.webp", credit: "User:Hyderabadi biryani, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hyderabadi_Biryani_2.jpg" },
  "Kashmiri Pulao": { photo: "kashmiri-pulao.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kashmiri_Pulao_(cropped).JPG" },
  "Curd Rice": { photo: "curd-rice.webp", credit: "Sudharshan Shanmugasundaram, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Curd_Rice.jpg" },
  "Mushroom Biryani": { photo: "mushroom-biryani.webp", credit: "Mohsinkt, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mushroom_Biryani.JPG" },
  "Ghee Rice": { photo: "ghee-rice.webp", credit: "Triv.rao, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Ghee_Rice.jpg" },
  "Bisibele Bath": { photo: "bisibele-bath.webp", credit: "Vidya pmysore, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mysore_style_bisibele_bath.jpg" },
  "Singapore Fried Rice": { photo: "singapore-fried-rice.webp", credit: "RM Bulseco from Davao City, Philippines., CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Fried_rice,_Singapore_-_20140215.jpg" },
  "Chicken Dum Biryani": { photo: "chicken-dum-biryani.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Dum_Biryani_03.jpg" },
  "Chicken Fried Rice": { photo: "chicken-fried-rice.webp", credit: "Vee Satayamas from Bangkok, Thailand, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Fried_rice_with_chicken_(17234644521).jpg" },
  "Chicken Hyderabadi Biryani": { photo: "chicken-hyderabadi-biryani.webp", credit: "Dheerajk88, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chicken_Hyderabadi_Biryani.JPG" },
  "Egg Fried Rice": { photo: "egg-fried-rice.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Egg_Fried_Rice.jpg" },
  "Plain Paratha": { photo: "plain-paratha.webp", credit: "Rupamdas75, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Methi_(fenugreek)_parathas.jpg" },
  "Bhatura": { photo: "bhatura.webp", credit: "[https://www.flickr.com/people/12261156@N00 Michael Cot�] from Austin, Texas, Texas, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bhatura.jpg" },
  "Naan": { photo: "naan.webp", credit: "Shisma, CC BY 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Naan_2.jpg" },
  "Butter Naan": { photo: "butter-naan.webp", credit: "Ganesh Mohan T, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Butter_Naan_2.jpg" },
  "Stuffed Naan": { photo: "stuffed-naan.webp", credit: "Kondiba shinde, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Stuffed_Naan.JPG" },
  "Tandoori Roti": { photo: "tandoori-roti.webp", credit: "Ravi Dwivedi, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Tandoori-rotis.jpg" },
  "Kulcha": { photo: "kulcha.webp", credit: "Divya Kudua, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paneer_Kulcha_Baking.jpg" },
  "Aloo Kulcha": { photo: "aloo-kulcha.webp", credit: "Priyanshi pb, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_Kulcha.jpg" },
  "Mix Kulcha": { photo: "mix-kulcha.webp", credit: "Foody1989, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mix_veg_with_garlic_kulcha.jpg" },
  "Rumali Roti": { photo: "rumali-roti.webp", credit: "Unknown author, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Rumali_roti.jpg" },
  "Lacha Paratha": { photo: "lacha-paratha.webp", credit: "Fatimahope, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Lacha_paratha.jpg" },
  "Methi Paratha": { photo: "methi-paratha.webp", credit: "Dharmadhyaksha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Methi_Parathas.JPG" },
  "Chapathi": { photo: "chapathi.webp", credit: "Ashok Kumar P S, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chapathi.jpg" },
  "Missi Roti": { photo: "missi-roti.webp", credit: "Sumit Surai, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Missi_Roti.jpg" },
  "Green Salad": { photo: "green-salad.webp", credit: "Andy Li, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Green_Salad_-_Flat_Iron_2026-02-24.jpg" },
  "Greek Salad": { photo: "greek-salad.webp", credit: "Geoff Peters from Vancouver, BC, Canada, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Greek_salad_(5178297958).jpg" },
  "Russian Salad": { photo: "russian-salad.webp", credit: "Miansari66, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Russian_Salad..JPG" },
  "Pasta Salad": { photo: "pasta-salad.webp", credit: "Brynn, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pasta_salad_closeup.JPG" },
  "Corn & Bean Salad": { photo: "corn-and-bean-salad.webp", credit: "Daniel Sone (Photographer), Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Corn_and_black_bean_salad.jpg" },
  "Coleslaw Salad": { photo: "coleslaw-salad.webp", credit: "MaiDenzel, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Readily_made_Coleslaw_salad_01.jpg" },
  "Watermelon and Feta Salad": { photo: "watermelon-and-feta-salad.webp", credit: "Shoshanah, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Watermelon_%26_Feta_Salad.jpg" },
  "Fresh Salad Bar": { photo: "fresh-salad-bar.webp", credit: "PattayaPatrol, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:DZ3_0604_A_colorful_self-serve_salad_bar_with_fresh_greens_chopped_vegetables_and_toppings_neatly_arranged_in_stainless_steel_trays.jpg" },
  "Moong Dal Kosambari": { photo: "moong-dal-kosambari.webp", credit: "Vidya pmysore, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Totapuri_moong_dal_kosambari.jpg" },
  "Papad": { photo: "papad.webp", credit: "Navaneeth Krishnan S, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Papad_(roasted).jpg" },
  "Pudina Chutney": { photo: "pudina-chutney.webp", credit: "Ramesh NG, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pudina_Chutney.jpg" },
  "Raita": { photo: "raita.webp", credit: "Bssasidhar, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Onion_raita(Close_up).jpg" },
  "Boondi Raita": { photo: "boondi-raita.webp", credit: "Ravi Dwivedi, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Boondi_Raita.jpg" },
  "Plain Curd": { photo: "plain-curd.webp", credit: "5boi38, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Plain_Curd_Rice.jpg" },
  "Coconut Chutney": { photo: "coconut-chutney.webp", credit: "Balurbala, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Coconut_Chutney_(Indian_Cuisine).jpg" },
  "Gulab Jamun": { photo: "gulab-jamun.webp", credit: "Cabeza2000, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Gulab_jamun_(Gibraltar,_November_2020).jpg" },
  "Kala Jamun": { photo: "kala-jamun.webp", credit: "Patelaahil, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kala_jamun.jpg" },
  "Rasgulla": { photo: "rasgulla.webp", credit: "Prakrutim, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Rasgulla_With_Rabdi.jpg" },
  "Gajar Ka Halwa": { photo: "gajar-ka-halwa.webp", credit: "Sharvarism, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Delicious_Gajar_Ka_Halwa.jpg" },
  "Beetroot Halwa": { photo: "beetroot-halwa.webp", credit: "Gopinath, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Beetroot_halwa.png" },
  "Moong Dal Halwa": { photo: "moong-dal-halwa.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Moong_Dal_Halwa_2023.jpg" },
  "Fruit Salad": { photo: "fruit-salad.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Fruit_Salad_4.jpg" },
  "Rice Kheer": { photo: "rice-kheer.webp", credit: "Swayampurna, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kheer_or_rice_pudding.jpg" },
  "Pineapple Pastry": { photo: "pineapple-pastry.webp", credit: "Mk2010, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pineapple_Pastry.JPG" },
  "Pumpkin Kheer": { photo: "pumpkin-kheer.webp", credit: "Dilip2292, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pumpkin_kheer.jpg" },
  "Semiya Payasam": { photo: "semiya-payasam.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Semiya_payasam_2023.jpg" },
  "Payasam": { photo: "payasam.webp", credit: "Ross thres, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paal_payasam.JPG" },
  "Dry Fruit Kheer": { photo: "dry-fruit-kheer.webp", credit: "Yuvraj Singh 97, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mixed_Dry_Fruit_Kheer_-_Home_-_Chandigarh_-_India_-_00011.jpg" },
  "Champakali": { photo: "champakali.webp", credit: "Vis M, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Champakali.jpg" },
  "Malai Sandwich": { photo: "malai-sandwich.webp", credit: "Silpa11, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Malai_Sandwich_-_Bikash_Babu_Sweets_-_Trivandrum,_Kerala_-_DSC_0016.jpg" },
  "Phirni": { photo: "phirni.webp", credit: "Anusruta, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Phirni_AD.jpg" },
  "Fruit Kebab": { photo: "fruit-kebab.webp", credit: "IndayLiburan, CC BY 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Fruit_Kebabs%22.jpg" },
  "Cup Cake": { photo: "cup-cake.webp", credit: "Saudarh2, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Cup_cake.png" },
  "Swiss Roll": { photo: "swiss-roll.webp", credit: "Ocdp, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Swiss_roll_003.jpg" },
  "Kashi Halwa": { photo: "kashi-halwa.webp", credit: "Harsha K R, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Halwa_Kashi_Sweets_of_India.jpg" },
  "Holige": { photo: "holige.webp", credit: "No machine-readable author provided. Pamri assumed (based on copyright claims)., Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Coconut_holige.jpg" },
  "Chiroti": { photo: "chiroti.webp", credit: "Gpkp, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chiroti_(RR_Nagar,_Bangalore,_2026).jpg" },
  "Pheni": { photo: "pheni.webp", credit: "Wajid Shah, VOA Urdu, Public domain, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pheni_2020_Rawalpindi.png" },
  "Mysore Pak": { photo: "mysore-pak.webp", credit: "Charles Haynes, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mysore_pak.jpg" },
  "Motichur Laddu": { photo: "motichur-laddu.webp", credit: "नाहयान, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Motichur_Laddu_(1).jpg" },
  "Badusha": { photo: "badusha.webp", credit: "Thamizhpparithi Maari, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Badusha.jpg" },
  "Badam Puri": { photo: "badam-puri.webp", credit: "Pratha Bopche, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Badam_puri_sweet.jpg" },
  "Chandrakala": { photo: "chandrakala.webp", credit: "Thamizhpparithi Maari, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chandrakala_sweet.jpg" },
  "Jalebi": { photo: "jalebi.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Jalebi_1.jpg" },
  "Suji Halwa": { photo: "suji-halwa.webp", credit: "Sushreebbsr, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Suji_Halwa-Odisha.jpg" },
  "Vanilla Ice Cream": { photo: "vanilla-ice-cream.webp", credit: "MichalPL, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Vanilla_ice_cream.jpg" },
  "Chocolate Ice Cream": { photo: "chocolate-ice-cream.webp", credit: "Nive Selvaraju, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chocolate_Ice_cream.jpg" },
  "Strawberry Ice Cream": { photo: "strawberry-ice-cream.webp", credit: "Zuxra.bmr, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Strawberry_ice-cream.jpg" },
  "Dry Fruit Kulfi": { photo: "dry-fruit-kulfi.webp", credit: "Vidya pmysore, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dry_fruits_kulfi_ice_cream.jpg" },
  "Cotton Candy": { photo: "cotton-candy.webp", credit: "FocalPoint, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG" },
  "Idli": { photo: "idli.webp", credit: "Unknown author, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Idli.jpg" },
  "Mini Idli": { photo: "mini-idli.webp", credit: "Nitin Desai, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mini_Idlis.JPG" },
  "Vada": { photo: "vada.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Vada_Food.jpg" },
  "Poori Sagu": { photo: "poori-sagu.webp", credit: "Wikichethan, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Poori_Sagu_Karnataka_Kannada_%E0%B2%AA%E0%B3%82%E0%B2%B0%E0%B2%BF_%E0%B2%B8%E0%B2%BE%E0%B2%97%E0%B3%81_%E0%B2%95%E0%B2%A8%E0%B3%8D%E0%B2%A8%E0%B2%A1.jpg" },
  "Masala Dosa": { photo: "masala-dosa.webp", credit: "Marajozkee, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Masala_dosa_01.jpg" },
  "Set Dosa": { photo: "set-dosa.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Set_Dosa_1.jpg" },
  "Podi Dosa": { photo: "podi-dosa.webp", credit: "Manukrishnan80, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Podi_Dosa_(73144).jpg" },
  "Plain Dosa": { photo: "plain-dosa.webp", credit: "Vivekdoshi11, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dosa_(Plain).jpg" },
  "Vegetable Upma": { photo: "vegetable-upma.webp", credit: "Priya1Iyer, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Vegetable_Upma.JPG" },
  "Semiya Upma": { photo: "semiya-upma.webp", credit: "Maharana7573, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Semiya_Upma_1.jpg" },
  "Kesaribath": { photo: "kesaribath.webp", credit: "Udaykumar236, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kesaribath.jpg" },
  "Poha": { photo: "poha.webp", credit: "Gannu03, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Poha_4.jpg" },
  "Indori Poha": { photo: "indori-poha.webp", credit: "Kxnyshk, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Indori_Poha,_New_Delhi.jpg" },
  "Upma": { photo: "upma.webp", credit: "Nokib Sarkar, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Rava_Upma.jpg" },
  "Aloo Paratha": { photo: "aloo-paratha.webp", credit: "Gannu03, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_Paratha_(96238).jpg" },
  "Paneer Paratha": { photo: "paneer-paratha.webp", credit: "rovingl, CC BY 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Awadhi_palak_paneer_paratha_dahi.jpg" },
  "Gobi Paratha": { photo: "gobi-paratha.webp", credit: "Daderot, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_gobi_paratha_-_Massachusetts.jpg" },
  "Sandwich": { photo: "sandwich.webp", credit: "Gaurav Dhwaj Khadka, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Sandwich_1.jpg" },
  "Mini Croissants": { photo: "mini-croissants.webp", credit: "Ceeseven, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Mini_Croissants.JPG" },
  "Danish Pastries": { photo: "danish-pastries.webp", credit: "Matt @ PEK from Taipei, Taiwan, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Danish_pastries_(5226580301).jpg" },
  "Corn Flakes with Milk": { photo: "corn-flakes-with-milk.webp", credit: "Th78blue, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kellogg%27s_Corn_Flakes,_with_milk.jpg" },
  "Garlic Bread": { photo: "garlic-bread.webp", credit: "Infrogmation, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Garlic_bread_baguettes_2.jpg" },
  "Toast with Butter": { photo: "toast-with-butter.webp", credit: "Gannu03, CC BY-SA 3.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Butter_Toast.jpg" },
  "Muffins": { photo: "muffins.webp", credit: "Bycro, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Muffins_02.jpg" },
  "Appam with Veg Stew": { photo: "appam-with-veg-stew.webp", credit: "Pranchiyettan, CC BY-SA 2.5 in, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:GKN_Appam_Veg_Stew_DSC_1292.JPG" },
  "Paddu": { photo: "paddu.webp", credit: "Soumendra Kumar Sahoo, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Paddu.jpg" },
  "Gol Gappe": { photo: "gol-gappe.webp", credit: "Anshulavohra, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Gol_gappe_(North_Indian_Style).JPG" },
  "Bhalla Papri": { photo: "bhalla-papri.webp", credit: "Nitin Badhwar from Dubai, UAE, CC BY-SA 2.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bhalla_Papri_Chaat_with_saunth_chutney.jpg" },
  "Dahi Poori": { photo: "dahi-poori.webp", credit: "Thangalavanya, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Dahi_poori.JPG" },
  "Dahi Papri Chaat": { photo: "dahi-papri-chaat.webp", credit: "Nithyasrm, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Delicious_Dahi_papri_chaat.JPG" },
  "Sev Puri": { photo: "sev-puri.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Sev_Puri_2023.jpg" },
  "Bhel Puri": { photo: "bhel-puri.webp", credit: "Sandhiya Rangasami, CC BY 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Bhel_puri_Snack.jpg" },
  "Raj Kachori": { photo: "raj-kachori.webp", credit: "Puneet vivid, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Raj_Kachori_Haldiram.jpg" },
  "Aloo Tikki Chaat": { photo: "aloo-tikki-chaat.webp", credit: "Nanditamomai, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Aloo_Tikki_Chaat.JPG" },
  "Dabeli": { photo: "dabeli.webp", credit: "Jatan1992, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Kachchi_Dabeli.jpg" },
  "Masala Puri": { photo: "masala-puri.webp", credit: "Kaushik AP, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Masala_puri.jpg" },
  "Momos": { photo: "momos.webp", credit: "Ganesh Mohan T, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_Momos_3.jpg" },
  "Loaded Nachos": { photo: "loaded-nachos.webp", credit: "YKanchan07, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Veg_loaded_nachos_made_by_me.jpg" },
  "Paan": { photo: "paan.webp", credit: "Gpkp, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Chocolate_paan_(2026)_03.jpg" },
  "Popcorn": { photo: "popcorn.webp", credit: "ViajeroExtraviado, CC0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Popcorn_9.jpg" },
  "Pizza": { photo: "pizza.webp", credit: "Yakshitha, CC BY-SA 4.0, via Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Pizza_2023.jpg" },
};

const slug = (name: string) => name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/** The picture a catalog dish shows: its photo when it has one, otherwise its category's illustration. */
export function catalogImage(dishName: string, categoryName: string): { url: string; credit: string | null } {
  const photo = CATALOG_PHOTOS[dishName];
  if (photo) return { url: `/catalog/photos/${photo.photo}`, credit: `${photo.credit} (${photo.source})` };
  return { url: `/catalog/categories/${slug(categoryName)}.svg`, credit: null };
}
