import type { Metadata } from "next";
import { DM_Sans, Geist_Mono } from "next/font/google";
import { Agentation } from "agentation";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* suppressHydrationWarning: some browser extensions (e.g. ColorZilla)
          inject attributes like cz-shortcut-listen onto <body> before React
          hydrates — a real mismatch there is unavoidable and not a bug in
          this app. Scoped to this element only, not deep-tree suppression. */}
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
        {process.env.NODE_ENV !== "production" && <Agentation />}
      </body>
    </html>
  );
}
